name: Auto Assign Issues to Triage column in Sprint Planning Project Board

on:
  issues:
    types: [opened]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  issue_opened:
    name: issue_opened
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
        with:
          egress-policy: audit

      - name: 'Move issue to "Triage"'
        uses: leonsteinhaeuser/project-beta-automations@d1c1261558118c0876fdb2b57a649303925e5a70 # v2.1.0
        with:
          gh_token: ${{ secrets.MY_GITHUB_TOKEN }}
          organization: atsign-foundation
          project_id: 8
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: "Triage"
